language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: TYPE=Debug

    - os: linux
      dist: trusty
      sudo: required
      env: TYPE=Release
      
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"


before_install:
  - sudo apt-get install libssl-dev libgmp-dev build-essential cmake git -y
  - git clone https://github.com/emp-toolkit/emp-readme.git
  - bash ./emp-readme/scripts/install_relic.sh
  - bash ./emp-readme/scripts/install_emp-tool.sh

script:
  - cmake -DCMAKE_BUILD_TYPE=$TYPE . && make
  - ./run ./bin/mot 12345  
  - ./run ./bin/shot 12345  
