language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: TYPE=Debug

    - os: linux
      dist: trusty
      sudo: required
      env: TYPE=Release


before_install:
  - sudo apt-get install libssl-dev libgmp-dev build-essential cmake git -y
  - git clone https://github.com/emp-toolkit/emp-readme.git
  - bash ./emp-readme/scripts/install_relic.sh
  - bash ./emp-readme/scripts/install_emp-tool.sh

script:
  - cmake -DCMAKE_BUILD_TYPE=$TYPE . && make
  - ./run ./bin/mot 12345  
  - ./run ./bin/shot 12345  